package org.example.aiproject.openAI;

import lombok.Data;

import java.util.List;
/*
 This class was completely generated by Chat GPT
 See prompt and reply here: https://chat.openai.com/share/a48933a3-73d6-4fab-b4c9-fb46d6909b81
 */

@Data
public class ChatCompletionResponse {


    private String id;
    private String object;
    private long created;
    private String model;
    private List<Choice> choices;
    private Usage usage;

    @Data
    public static class Choice {
        private int index;
        private Message message;
        private String finish_reason;
    }

    @Data
    public static class Message {
        private String role;
        private String content;
    }

    @Data
    public static class Usage {
        private int prompt_tokens;
        private int completion_tokens;
        private int total_tokens;
    }


}
